services:
  - type: web
    name: creditrisk-api
    env: python
    buildCommand: ""
    startCommand: uvicorn API/main.py:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ENV
        value: production
